### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ghost** [PhantomAppDevelopment/socialmedia-as3#1]
Hi, i gave a try to your samples, for my case i turned them into an FDT project with AS3 only (no mxml) and tested them on Android, but encountered some problems

If you have a moment, can you check if they still run well for you, here's a small feedback of what i noticed

/////////////////////// FACEBOOK ////////////////////////////

ok on adb desktop test but 
error when testing on device

possibly because domain swap from www.facebook.com to m.facebook.com, didn't look much further

fail : [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032" errorID=2032]

location : 

https://m.facebook.com/login.php
?
skip_api_login=1
&
api_key=760382710781998
&
signed_next=1
&
next=https://m.facebook.com/v2.8/dialog/oauth?redirect_uri=https%3A%2F%2Fwww.facebook.com%2Fconnect%2Flogin_success.html
&
scope=public_profile
&
client_id=760382710781998
&
ret=login
&
logger_id=11fa5e73-1f48-4d85-83d3-91aeccd5a0cf
&
cancel_url=https://www.facebook.com/connect/login_success.html?error=access_denied
&
error_code=200
&
error_description=Permissions+error
&
error_reason=user_denied#_=_
&
display=touch&locale=fr_FR
&
logger_id=11fa5e73-1f48-4d85-83d3-91aeccd5a0cf
&
_rdr

may be I badly configured the app in the facebook dev portal for the mobile calls, but i don't think so

///////////////////////// GOOGLE ////////////////////////////

access is granted on both adb and android release but nothing else happens in changeLocation method

webview.title is 
'Authorisation Request'

webview.location is 
https://accounts.google.com/o/oauth2/approval?as=3c70b8e780af3580&pageId=none&xsrfsign=AMt42IIAAAAAWIlIq_rFCIdbWy7KVs3ujls3Z-LUhzYN

no 'code' property to call getAccessToken method

webview page displays 'The authorization was granted. Please switch to your application.'

////////////////////// INSTAGRAM ///////////////////////////

android release ok

/////////////////////// TWITTER ////////////////////////////

android release ok

**Comment by agentphantom** [comment]
Thank you for the heads up. I will do some tests on my end and report back what I found.

To be clear, it works fine on the AIR simulator but not in an Android device, right?

**Comment by agentphantom** [comment]
I tried and tested the Facebook and Google guides for several hours and was able to make a workaround for the Google login.

The Facebook login doesn't work, no matter what settings I use. I suggest to use the Firebase Auth guides instead:

https://github.com/PhantomAppDevelopment/firebase-as3/tree/master/auth/

These guides are easier and faster to implement and are future proof.

**Comment by ghost** [comment]
thanks, no matter, i had planned to look at firebase after this, btw i
tried further on facebook login, but whatever urls nor settings i try, no
way to get the redirection url with the code property

2017-01-28 0:25 GMT+01:00 Mr. Phantom <notifications@github.com>:
